version: 0.1.{build}

platform:
  - x64

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 6 x64
  - git reset --hard HEAD
  - nvm install 6
  - npm install electron-builder@next # force install next version to test electron-builder
  - npm install
  - npm prune

build_script:
  - node --version
  - npm --version
  - npm run release

test: off

artifacts:
  - path: '**\*.zip'
    name: win_release

deploy:
  release: $(appveyor_repo_tag_name)
  description: 'TransliterationApplication'
  provider: GitHub
  auth_token:
    secure: QBn6bw8znM2WsrG32eTzA55Iu0iE6oymujVBos6XFUldN/biNahd6Csr6d9Y4u+E
  artifact: win_release
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: true
